### PR TITLE
Update C and C++ syntax highlightings

### PR DESCRIPTION
**Pull request by data-man**
Keywords taken from:
https://en.cppreference.com/w/c/keyword
https://en.cppreference.com/w/cpp/keyword

### CODE REVIEW

**Comment by zyv** [comment]
Mentioned in https://midnight-commander.org/ticket/4524 so that it doesn't get completely lost forever.

**Comment by data-man** [comment]
> Mentioned in

Are there any plans to enable issues or discussions in this repository?

**Comment by zyv** [comment]
> > Mentioned in
> 
> Are there any plans to enable issues or discussions in this repository?

In general, yes, but no timelines due to lack of manpower.

**Comment by data-man** [comment]
> due to lack of manpower

Can MC-users help in any way?

**Pull request closed without merging**
