### PR TITLE
issue: mc trac commit links require username/password

### PR DESCRIPTION
**Pull request by rofl0r**
hi, sorry for using this "backdoor" to open an issue :)

i just today discovered this issue http://midnight-commander.org/ticket/3697#comment:15 and wanted to check out the referenced commit links, to find out if my netbsd-curses support patch broke anything and how it has been fixed, whether it was reverted, etc, but they're all password protected.

also notifying @ThomasDickey whose netbsd-curses writeup/critics i discovered today:
you mention some issues there which i cannot reproduce - UTF8 support works well for me, i've never seen a compilation fail due to __unused but i would be glad to fix it! also i'm not aware (neither is wikipedia from where i derived my knowledge) of any other than the 3 curses impls i mentioned, but then you're in this "business" since 20+ years... and as for the numbers in the README: the 128 MB result from the CFLAGS given in appendix A. it's mostly the combination of -ffunction-sections -fdata-sections + -g3 which bloat static libs quite a bit, but it's very effective in creating small static linked binaries (which i'm mainly interested in). anyhow, those numbers were taken during the very first days of netbsd-curses-portable, so i should probably redo them with current when i find time.

### CODE REVIEW

**Comment by rofl0r** [comment]
oh, sorry: i forgot to ask for a copy of bulgarian-utf8.txt, so i could try to reproduce the reported issue @ThomasDickey

**Comment by zyv** [comment]
@rofl0r long story short, your stuff broke ncurses and we initially had to re-add the old code guarded by a define, but it appears that @ThomasDickey has found a way to make it work in both `ncurses` and `netbsd-curses` without additional trickery and it's committed now in the current `master`.

The links have been put behind login because rogue bots kept DDoSing our Trac instance by crawling them no matter what, you can either see the code on GitHub, or else login with your Trac account.

**Comment by rofl0r** [comment]
are the commit hashes from that bug report valid for the github repo too ? if so, and since it appears that your trac server is so resource constrained it cannot even stand a few crawlers, you probably should link to the github commits instead.

**Comment by zyv** [comment]
> are the commit hashes from that bug report valid for the github repo too ? 

Of course they are, why wouldn't they!? GitHub is our canonical repository and all clones should have matching hashes anyways, unless they are corrupted.

> so resource constrained it cannot even stand a few crawlers

It is resource constrained, but when I'm saying "rogue bots are DDoS'in it", I really mean it. Even if it was a bit beefier, we have millions of URLs that are expensive to render, and I don't think that optimizing it for feeding dynamic pools of Asian IPs is not a waste.

> you probably should link to the github commits instead.

I was thinking about setting up redirects to GitHub for non-logged in users, but it's not so easy and I didn't have time for it yet. If you want to help me by giving a set of relevant nginx rules, it will be most appreciated.

**Pull request closed without merging**
