### PR TITLE
add support for kernel initrd images as vfs

### PR DESCRIPTION
**Pull request by eugenesan**
This utilizes already existing initrd suppport

### CODE REVIEW

**Comment by zyv** [comment]
In view of all these comments, I would suggest to replace your changes with simply the following:

```
regex//initrd\.img(-[^/]+)?$
    Open=%cd %p/ucpio://
```

Please tell me if this works for you and I will commit this, or else rebase / force-push this pull request.

**Comment by zyv** [comment]
http://www.midnight-commander.org/ticket/3578

**Comment by zyv** [comment]
Also, see http://www.midnight-commander.org/ticket/3115 .

**Comment by eugenesan** [comment]
Sorry for the mess. The original patch is pretty old and reviewing it now I agree, it is broken.
Here is the commit with your proposition: https://github.com/MidnightCommander/mc/commit/fc862b1665dfc1dfdfb816736b025eeb1e69e192

P.S.
http://www.midnight-commander.org/ticket/3115 is indeed original patch posting.

**Comment by zyv** [comment]
Fixed in master.

**Pull request closed without merging**
