### PR TITLE
Update pt_BR.po

### PR DESCRIPTION
**Pull request by marcelocripe**
Please accept the Brazilian Portuguese translation for the Midnight Commander program or use the translation I made in Transifex for the files mc_mcpot_pt_BR.po and mc_mc_hint_pt_BR.po.

The files that have the latest translation can also be found at these URLs: https://github.com/marcelocripe/Midnight_Commander_pt_BR/blob/main/mc_mcpot_pt_BR.po and
https://github.com/marcelocripe/Midnight_Commander_pt_BR/blob/main/mc_hint_pt_BR.po

I thank the Transifex administrator who approved my request to voluntarily translate Midnight Commander on Transifex for the Brazilian Portuguese language team.

I thank you for creating, maintaining and updating Midnight Commander.

Note: Midnight Commander is one of antiX Linux's default file managers. Our community has a .desktop file with the translation into several languages and can be obtained from this URL: https://gitlab.com/antix-contribs/antix-desktop-files/-/blob/main/.desktop/mc.desktop and https://gitlab.com/antix-contribs/antix-desktop-files/-/blob/main/.desktop/mcedit.desktop.

Thank you very much.

marcelocripe
(Original text in Brazilian Portuguese language)

- - - - -

Por favor, aceitem a tradução do idioma o Português do Brasil para o programa Midnight Commander ou utilizem a tradução que eu fiz no Transifex para os aquivos mc_mcpot_pt_BR.po e o mc_mc_hint_pt_BR.po.

Os arquivos que possuem a tradução mais recente também podem ser encontrados nestes URLs: https://github.com/marcelocripe/Midnight_Commander_pt_BR/blob/main/mc_mcpot_pt_BR.po e
https://github.com/marcelocripe/Midnight_Commander_pt_BR/blob/main/mc_hint_pt_BR.po

Eu agradeço ao administrador do Transifex que aprovou o meu pedido de traduzir voluntariamente o Midnight Commander no Transifex para a equipe do idioma Português do Brasil.

Eu agradeço por você criar, manter e atualizar o Midnight Commander.

Observação: O Midnight Commander é um dos gerenciadores de arquivos padrão do antiX Linux. A nossa comunidade possui um arquivo .desktop com a tradução para vários idiomas e pode ser obtido neste URL: https://gitlab.com/antix-contribs/antix-desktop-files/-/blob/main/.desktop/mc.desktop e https://gitlab.com/antix-contribs/antix-desktop-files/-/blob/main/.desktop/mcedit.desktop.
[mc.desktop_and_mcedit.desktop.zip](https://github.com/MidnightCommander/mc/files/10255046/mc.desktop_and_mcedit.desktop.zip)

Muito obrigado.

marcelocripe
(Texto original em idioma Português do Brasil)

Thank you for thinking about contributing to Midnight Commander, but we **ARE NOT** using pull requests to manage incoming patches!

Instead, please check out our Trac instance to see if the issue has already been reported, or submit a new ticket:

https://midnight-commander.org/wiki/NewTicket

If you chose to submit the pull request instead, keep in mind that we are not checking on them regularly, so it might take ages before we even get to it, if at all.

Unfortunately, GitHub does not allow us to disable the pull requests feature for this repository, so we have to warn you this way...

### CODE REVIEW

**Comment by zyv** [comment]
Thank you, but this PR is not necessary. The translations are managed via Transifex and the latest state is always pulled in during the release process.

**Comment by marcelocripe** [comment]
>Thank you, but this PR is not necessary. The translations are managed via Transifex and the latest state is always pulled in during the release process.

Hello zyv.

I managed to understand that the translations are managed via Transifex, I just didn't know how to let you know that I managed to complete the translation of my language ("pt_BR") for both the "mc_mcpot_pt_BR.po" and the "mc_mc_hint_pt_BR.po" files.

Thank you so much for merging and accepting my Transifex translations. I hope to get Midnight Commander on antiX Linux 23 with my translations. Its file manager is one of the "standard" programs used in the antiX Linux ISOs that are built by the anticapitalista who is the leader of this GNU/Linux distribution.

Please, could you also accept the ".desktop" file (mc.desktop.zip) translated by the antiX Linux community?

The "mc.desktop" file can also be obtained from this URL: https://gitlab.com/antix-contribs/antix-desktop-files/-/blob/main/.desktop/mc.desktop, but the entries are a little disorganized in relation to the file that I am sending you here.

The "de", "fr", "fr_BE", "it", "pt" and "pt_BR" languages from the "mc.desktop" file, I'm pretty sure were translated by native humans of the respective languages. The other languages were translated by the automatic translator and need to be proofread by native speakers of the respective languages. Please include this "mc.desktop" file if one does not already exist in the Midnight Commander source code. In this way, other people will be able to review the translations made by the automatic translator and Midnight Commander will benefit from these translations reflecting positively on the various GNU/Linux or BSD that use Midnight Commander.

Thank you very much.

[mc.desktop.zip](https://github.com/MidnightCommander/mc/files/10359758/mc.desktop.zip)

- - - - -

>Thank you, but this PR is not necessary. The translations are managed via Transifex and the latest state is always pulled in during the release process.

Olá zyv.

Eu consegui compreender que as traduções são gerenciadas via Transifex, eu só não sabia como te avisar que eu consegui concluir a tradução do meu idioma ("pt_BR") para ambos os arquivos "mc_mcpot_pt_BR.po" e o "mc_mc_hint_pt_BR.po".

Muito obrigado por você mesclar e aceitar as minhas traduções do Transifex. Eu espero poder receber o Midnight Commander no antiX Linux 23 com as minhas traduções. O seu gerenciador de arquivos é um dos pragramas "padrões" utilizados nas ISOs do antiX Linux que são construídas pelo anticapitalista que é o líder desta distribuição GNU/Linux.

Por favor, você poderia aceitar também o arquivo ".desktop" (mc.desktop.zip) traduzido pela comunidade do antiX Linux?

O arquivo "mc.desktop" também pode ser obtido neste URL: https://gitlab.com/antix-contribs/antix-desktop-files/-/blob/main/.desktop/mc.desktop, mas as entradas estão um pouco desorganizadas em relação ao arquivo que eu estou te enviando aqui.

Os idiomas "de", "fr", "fr_BE", "it", "pt" e "pt_BR" do arquivo "mc.desktop", eu tenho certeza que foram traduzidos por seres humanos nativos dos respectivos idiomas. Os outros idiomas foram traduzidos pelo tradutor automático e precisam ser revisados por nativos dos respectivos idiomas. Por favor, inclua este arquivo "mc.desktop", caso ainda não exista um no código fonte do Midnight Commander. Desta forma outras pessoas poderão revisar as traduções feitas pelo tradutor automático e o Midnight Commander será beneficiado com estas traduções refletindo positivamente nos diversos GNU/Linux ou BSD que utilizem o Midnight Commander.

Muito obrigado.

**Comment by aborodin** [comment]
> Please, could you also accept the ".desktop" file (mc.desktop.zip) translated by the antiX Linux community?

The .desktop file should be generated from some .desktop.in, propagating translations from *.po files as it done in other projects.
https://midnight-commander.org/ticket/2314

**Comment by zyv** [comment]
We will consider it, thank you, but it's quite a lot of work to do it properly, so it won't make it in the next release.

**Comment by marcelocripe** [comment]
> We will consider it, thank you, but it's quite a lot of work to do it properly, so > it won't make it in the next release.

The automatic translation of your answer was not fully understandable.

It would be better if you write here in your native language and with more details so that I can understand better.

So I'm going to register at https://midnight-commander.org/ticket/2314.
I don't know how I can add language translations to the "mc.desktop", "MidnightCommander.desktop" and mc.desktop files. Can I attach the ".desktop" files I have with the translations made by the antiX community by keeping the existing translations on https://midnight-commander.org/ticket/2314?

When programmers do not provide translated ".desktop" files, it is up to packagers to include or not include translations. And that's where the problem occurs, because most packagers think exactly like me, that the translations have to come from the "upstream". There are few packagers that accept to receive translations by e-mail or in the forums, and most of the time the packagers do not accept to receive translations. This creates problems for us volunteer translators, because we can't get GNU/Linux translated into more and more languages and the lack of translations drives end users away from Free Software - this is the main problem that prevents GNU/Linux from growing here in Brazil. Furthermore, without the translations, no one will understand what the Midnight Commander text editor or MidnightCommander file manager is and what it is for.

- - - - -

Die automatische Übersetzung Ihrer Antwort war nicht ganz verständlich.

Es wäre besser, wenn Sie hier in Ihrer Muttersprache und mit mehr Details schreiben, damit ich es besser verstehen kann.

Also melde ich mich unter https://midnight-commander.org/ticket/2314 an.
Ich weiß nicht, wie ich Sprachübersetzungen zu den Dateien "mc.desktop", "MidnightCommander.desktop" und mc.desktop hinzufügen kann. Kann ich die „.desktop“-Dateien, die ich mit den Übersetzungen der AntiX-Community habe, anhängen, indem ich die vorhandenen Übersetzungen auf https://midnight-commander.org/ticket/2314 behalte?

Wenn Programmierer keine übersetzten ".desktop"-Dateien bereitstellen, liegt es an den Paketierern, Übersetzungen einzuschließen oder nicht. Und genau da tritt das Problem auf, denn die meisten Paketierer denken genau wie ich, dass die Übersetzungen vom "Upstream" kommen müssen. Es gibt nur wenige Paketanbieter, die akzeptieren, Übersetzungen per E-Mail oder in den Foren zu erhalten, und meistens akzeptieren die Paketanbieter den Empfang von Übersetzungen nicht. Das schafft Probleme für uns freiwillige Übersetzer, weil wir GNU/Linux nicht in immer mehr Sprachen übersetzen lassen und der Mangel an Übersetzungen die Endnutzer von Freier Software abhält – das ist das Hauptproblem, das das Wachstum von GNU/Linux verhindert hier in Brasilien. Außerdem wird ohne die Übersetzungen niemand verstehen, was der Midnight Commander-Texteditor oder der MidnightCommander-Dateimanager ist und wozu er dient.

- - - - -

> We will consider it, thank you, but it's quite a lot of work to do it properly, so > it won't make it in the next release.

A tradução automática da sua resposta não ficou totalmente compreensível. 

Seria melhor se você escrevesse aqui em seu idioma natal e com mais detalhes para eu conseguir compreender melhor.

Então eu vou fazer o cadastro no https://midnight-commander.org/ticket/2314.
Eu não sei como posso adicionar as traduções dos idomas no arquivo "mc.desktop", no "MidnightCommander.desktop" e no mc.desktop. Eu posso anexar os arquivos ".desktop" que eu tenho com as traduções feitas pela comunidade antiX mantendo as traduções existentes no https://midnight-commander.org/ticket/2314?

Quando os programadores não disponibilizam os aquivos ".desktop" traduzidos, fica a critério dos empacotadores incluir ou não as traduções. E é aí que ocorre o problema, porque a maioria dos empacotadores pensam exatamente como eu, que tem que vir do "upstream" as traduções. São poucos os empacotadores que aceitam receber as traduções por e-mail ou nos fóruns, sendo que na maioria das vezes os empacotadores não aceitam receber as traduções. Isso cria problemas para nós tradutores voluntários, porque não conseguimos tornar o GNU/Linux cada vez mais traduzido em vários idiomas e a falta das traduções afastam os usuários finais do Free Software - este é o principal problema que impede o crescimento do GNU/Linux aqui no Brasil. Além do mais, sem as traduções, ninguém vai compreender o que é e para que serve o editor de texto do Midnight Commander ou o gerenciador de arquivos do MidnightCommander.

**Comment by zyv** [comment]
> A tradução automática da sua resposta não ficou totalmente compreensível.

We tried to explain you that integrating a desktop-file correctly is a technically difficult task. It's not as simple as taking your file and adding it to the repository. We have a ticket for that, but we can't tell you when this will be done.

> Seria melhor se você escrevesse aqui em seu idioma natal e com mais detalhes para eu conseguir compreender melhor.

Well, which other languages do you speak? I can only read Portuguese, but I don't speak it. I can only offer English, German, French or Russian.

**Comment by marcelocripe** [comment]
>I can only offer English, German, French or Russian.
Machine translation usually works best when the text is written in the language you are most proficient in, i.e. your native language. Since I rely on machine translation to communicate, the more detailed information the text contains, the better I can understand it.

For example, the texts in pt_BR that I entered in Transifex are a construction of the automatic translation of the languages "en", "ru" (that's what I got the best texts), "de" and "es".

Is it serious that you write in 5 different languages?

Or is it DeepL or Leo machine translation?

When programmers do not provide translated ".desktop" files, it is up to packagers to include or not include translations. And that's where the problem occurs, because most packagers think exactly like me, that the translations have to come from the "upstream". There are few packagers that accept to receive translations by e-mail or in the forums, and most of the time the packagers do not accept to receive translations. This creates problems for us volunteer translators, because we can't get GNU/Linux translated into more and more languages and the lack of translations drives end users away from Free Software - this is the main problem that prevents GNU/Linux from growing here in Brazil. Furthermore, without the translations, no one will understand what the Midnight Commander text editor or MidnightCommander file manager is and what it is for.

- - - - -

>I can only offer English, German, French or Russian.
Normalmente a tradução automática funciona melhor quando o texto é escrito no idioma que você domina mais, ou seja, o seu idioma nativo. Como eu dependo da tradução automática para me comunicar, quando mais informações detalhadas o texto conter, melhor será a minha compreensão.

Por exemplo, os textos em pt_BR que eu inseri no Transifex são uma construção da tradução automática dos idiomas "en", "ru" (foi o que eu obtive os melhores textos), "de"  e "es".

É sério que você escreve em 5 idiomas diferentes?

Ou é a tradução automática do DeepL ou do Leo?

Quando os programadores não disponibilizam os aquivos ".desktop" traduzidos, fica a critério dos empacotadores incluir ou não as traduções. E é aí que ocorre o problema, porque a maioria dos empacotadores pensam exatamente como eu, que tem que vir do "upstream" as traduções. São poucos os empacotadores que aceitam receber as traduções por e-mail ou nos fóruns, sendo que na maioria das vezes os empacotadores não aceitam receber as traduções. Isso cria problemas para nós tradutores voluntários, porque não conseguimos tornar o GNU/Linux cada vez mais traduzido em vários idiomas e a falta das traduções afastam os usuários finais do Free Software - este é o principal problema que impede o crescimento do GNU/Linux aqui no Brasil. Além do mais, sem as traduções, ninguém vai compreender o que é e para que serve o editor de texto do Midnight Commander ou o gerenciador de arquivos do MidnightCommander.

**Comment by marcelocripe** [comment]
I really want to be able to have all the "standard" antiX programs translated into my language, but unfortunately some programmers don't want to receive the translations, namely HerbstluftWM, Celluloid, MPV, Firejail, DeSmuME and others.

In the antiX community we have volunteer translators who are dedicated people who work hard to bring translations to all speakers of their languages "de", "fr", "fr_BE", "it", "pt" and "pt_BR". Recently, we had the pleasure to welcome another volunteer translator, this time it was from Hungarian - https://www.antixforum.com/forums/topic/hungarian-translation/. At some point he will reach the Midnight Commander.

As soon as I manage to complete the translation of "xnc.hlp" into pt_BR I will be able to send you here in this conversation or request the inclusion of a new file. You choose how you prefer to receive the translated file.

- - - - -

Eu quero muito poder ter todos os programas "padrões" do antiX traduzidos em meu idioma, mas alguns programadores infelizmente não querem receber as traduções, sendo eles o HerbstluftWM, Celluloid, MPV, Firejail, DeSmuME e outros.

Na  comunidade antiX temos tradutores voluntários que são pessoas dedicadas que se esforçam muito para levar as traduções para todos os falantes dos seus idiomas "de", "fr", "fr_BE", "it", "pt" e "pt_BR". Recentemente, nós tivemos o prazer de receber mais um tradutor voluntário, desta vez foi do idioma Húngaro - https://www.antixforum.com/forums/topic/hungarian-translation/. Em algum momento ele chegará até o Midnight Commander.

Assim que eu conseguir concluir a tradução do "xnc.hlp" em pt_BR eu poderei te enviar aqui nesta conversa ou fazer o pedido de inclusão de um novo aquivo. Você escolhe como prefere receber o arquivo traduzido.

**Comment by zyv** [comment]
> Is it serious that you write in 5 different languages?

No, it's just 4 languages, unfortunately. I can read a few other European languages, because they are part of the same family, but I don't speak them.

> As soon as I manage to complete the translation of "xnc.hlp" into pt_BR I will be able to send you here in this conversation or request the inclusion of a new file. You choose how you prefer to receive the translated file.

Please don't do this. This file is automatically generated from the man pages:

https://github.com/MidnightCommander/mc/tree/master/doc/man

If you want, you can translate the man pages and open a ticket at midnight-commander.org for us to include them. Sadly, I didn't manage to make enough time until now to make it possible to translate and update the man pages via Transifex.

**Comment by aborodin** [comment]
> This file is automatically generated from the man pages:

No. xnc.hlp is one of two source files for internal help: see doc/hlp/*/xnc.hlp
Second source is mc.1:
https://github.com/MidnightCommander/mc/blob/master/doc/hlp/Makefile.am#L13

**Comment by marcelocripe** [comment]
> No, it's just 4 languages, unfortunately. I can read a few other European 
> languages, because they are part of the same family, but I don't speak them.

Even if you don't speak, reading is already something very good. Here in Brazil, I only have contact with the Spanish language of emigrants from Bolivia and Argentina and the English language that is forced by the media.

> Please don't do this. This file is automatically generated from the man pages:

The file was ready before your answer, if you still want it, I can send it to you here.


> Please don't do this. This file is automatically generated from the man pages:

> https://github.com/MidnightCommander/mc/tree/master/doc/man

If I understood correctly, the file I have to translate is "mc.1.in". Please, could you tell me what language you wrote the "mc.1.in" file for, so I can take the language you master the most as a reference. Normally, one language among the four tends to be more detailed and this will be the best language for me to use as a reference to build the pt_BR texts.

Are there any other files besides the "mc.1.in" file that I can translate?

- - - - -

> No, it's just 4 languages, unfortunately. I can read a few other European 
> languages, because they are part of the same family, but I don't speak them.

Mesmo que você não fale, ler já é algo muito bom. Aqui no Brasil, eu só tenho contato com o idioma Espanhol dos emigrantes da Bolívia e da Argentina e o idioma Inglês que é forçado pela mídias.

> Please don't do this. This file is automatically generated from the man pages:

O arquivo ficou pronto antes da sua resposta, se mesmo assim você o quiser, eu posso te enviar aqui.


> Please don't do this. This file is automatically generated from the man pages:

> https://github.com/MidnightCommander/mc/tree/master/doc/man

Se eu consegui compreender corretamente, o arquivo que eu tenho que traduzir é o  "mc.1.in". Por favor, você poderia me dizer qual é o idioma que você escreveu o arquivo  "mc.1.in" para eu tomar como referência o idioma que você domina mais. Normalmente, um idioma entre os quatro você costuma ser mais detalhista e este será o melhor idioma para eu utilziar como referência para construir os textos pt_BR.

Existe mais algum outro arquivo, além do arquivo  "mc.1.in" que eu possa traduzir?

[xnc_pt_BR.hlp.zip](https://github.com/MidnightCommander/mc/files/10373065/xnc_pt_BR.hlp.zip)

**Comment by marcelocripe** [comment]
Hello zyv and aborodin.

I'm returning here to let you know that I needed to make some improvements to the "pt_BR" text in Tranisfex's "mc-hint--master_pt_BR.po" file because of some texts similar to this one:

> msgid "Hint: Use C-x p to copy the current pathname to the command line."

The key combination does not include the minus "-" or the dash, I believe the text could be better explained, for example:

> msgid "Tip: Simultaneously press the C key together with the X key, then press the P key to copy the current path name to the command line."

I will continue translating the mc.1.in file into pt_BR to send to you.

- - - - -

Olá zyv e aborodin.

Eu estou retornando aqui para avisá-los que eu precisei fazer algumas melhorias no texto "pt_BR" no arquivo "mc-hint--master_pt_BR.po" do Tranisfex por causa de alguns textos semelhantes a este:

> msgid "Hint: Use C-x p to copy the current pathname to the command line."

A combinação de teclas não inclui o "-" menos ou o traço, acredito que o texto poderia ser melhor explicado, por exemplo:

> msgstr "Dica: Pressione simultaneamente a tecla C junto com a tecla X, em seguida, pressione a tecla P para copiar o nome do caminho atual para a linha de comando."

Eu vou continuar traduzindo o arquivo mc.1.in em pt_BR para enviar para vocês.

**Pull request closed without merging**
