### PR TITLE
added support for cobol.

### PR DESCRIPTION
**Pull request by alexbodn**
it looks good for learning cobol.
i thank you for your warning and for providing midnight commander in general.
i was not able the pass the captcha on your trac, so my only option was to request this pull.

Thank you for thinking about contributing to Midnight Commander, but we **ARE NOT** using pull requests to manage incoming patches!

Instead, please check out our Trac instance to see if the issue has already been reported, or submit a new ticket:

https://midnight-commander.org/wiki/NewTicket

### CODE REVIEW

**Comment by zyv** [comment]
@alexbodn the syntax-file itself is missing.

**Comment by aborodin** [comment]
Please use https://midnight-commander.org/ticket/1987 instead of create new ticket.

**Comment by alexbodn** [comment]
i have added the cobol.syntax file to the commit, thanks

**Comment by alexbodn** [comment]
> Please use https://midnight-commander.org/ticket/1987 instead of create new ticket.

i appologize, but i can't pass the captcha on the mc trac site.
but i do write by hand, here and there ;).

**Comment by aborodin** [comment]
61691ea3e8a382ec9ad285384d1c4e75f6fed489

Thanks!

**Pull request closed without merging**
