### PR TITLE
Bug fix - missing #include when building against musl

### PR DESCRIPTION
**Pull request by dimkr**

### CODE REVIEW

**Comment by aborodin** [comment]
Why ttydefaults.h is required?
Some systems haven't it: https://lists.gnu.org/archive/html/gpsd-dev/2015-06/msg00032.html

**Comment by aborodin** [comment]
About 7 year later. :-)
Is this PR still actual? If yes, what compilation error is fixed here?

**Comment by dimkr** [comment]
> Is this PR still actual?

I guess not, but Alpine has a patch (https://git.alpinelinux.org/aports/tree/main/mc/fix-cchar_t.patch?id=2b6a04f7fe009ec2e5d4781106639fabf603fc5b) that can be upstreamed. Not sure it fixes the same problem.

**Comment by aborodin** [comment]
Thanks.

> that can be upstreamed

That patch is not actual anymore because of ba62dd32add2767d6d13f9abb82f43304418740f.

**Pull request closed without merging**
