### PR TITLE
Reimplement xorriso part of iso9660 listing

### PR DESCRIPTION
**Pull request by slowpeek**
When xorriso is installed, iso9660 listing was done with `xorriso .. -lsl ..` per dir recursively. It was unbearably slow on iso images with lots of subdirs. For example, it took my machine 2 minutes to open debian-12.5.0-amd64-DVD-1.iso which contains 2627 dirs. This commit makes use of `xorriso .. -find / -exec lsdl ..` instead to list the whole directory tree in a single pass.

Also, parsing of xorriso output has been reworked and as a result such previously missing items became visible in the listing:
- symlinks
- the boot catalog file

---

Here is how you can see why the current iso9660 extfs code takes so long to open debian-12.5.0-amd64-DVD-1.iso:

- have xorriso installed
- create `/tmp/xorriso` with such code

  ``` sh
  #!/bin/sh

  echo "$(date +'%H:%M:%S') xorriso $*" >> /tmp/log
  exec /usr/bin/xorriso "$@"
  ```
- make the file executable
- start mc as `PATH=/tmp:$PATH mc`
- open another terminal window, create the log file with `touch /tmp/log` and run `tail -fn0 /tmp/log` to follow any writes to it
- in mc: navigate to the dir containing the iso, select it and press Enter
- watch the log lines in the other window
 
[sample log](https://github.com/MidnightCommander/mc/files/15123257/log.txt)

### CODE REVIEW

**Comment by zyv** [comment]
Could you please at least add tests to `tests/src/vfs/extfs/helpers-list/data` after such extensive changes to `iso9660`? Thanks.

**Comment by zyv** [comment]
Mentioned in https://midnight-commander.org/ticket/4524#comment:7

**Comment by zyv** [comment]
The correct ticket reference is as follows:

https://midnight-commander.org/ticket/3570

**Comment by zyv** [comment]
What is `lsdl`? I also don't have it on my machine and I can't seem to find anything with cursory googling @slowpeek

**Comment by slowpeek** [comment]
@zyv  `lsdl` is one of xorriso's find's -exec's options:

```
> xorriso -dev debian-12.5.0-amd64-DVD-1.iso -find / -exec lsdl 2>/dev/null | head
dr-xr-xr-x    1 0        0               0 Feb 10 14:53 '/'
dr-xr-xr-x    1 0        0               0 Feb 10 14:53 '/.disk'
-r--r--r--    1 0        0               5 Feb 10 13:33 '/.disk/base_components'
-r--r--r--    1 0        0               0 Feb 10 13:37 '/.disk/base_installable'
-r--r--r--    1 0        0               4 Feb 10 13:33 '/.disk/cd_type'
dr-xr-xr-x    1 0        0               0 Feb 10 13:33 '/.disk/id'
-r--r--r--    1 0        0               0 Feb 10 13:33 '/.disk/id/61b76f0c-f287-4af2-a2e2-da3fc92af5cc'
-r--r--r--    1 0        0              93 Feb 10 13:33 '/.disk/info'
-r--r--r--    1 0        0            1131 Feb 10 14:53 '/.disk/mkisofs'
-r--r--r--    1 0        0              34 Feb 10 13:33 '/.disk/udeb_include'
```

**Comment by zyv** [comment]
@aborodin so it seems that it's not an external dependency, but built in into xorriso.

@slowpeek can you provide test data for this vfs like I linked?

**Comment by slowpeek** [comment]
Btw there is one more, kinda very bad issue with xorriso in the iso9660 vfs script. When modifying an iso image, by default xorriso does NOT keep el torito and joliet stuff. For example, this function from the vfs script in addition to removing some file from the image, makes the image not bootable (if it was) AND drops the joliet tree (if it was there):

```
xorriso_rm() {
    if test -z "$XORRISO"; then
        return 1
    fi
    $XORRISO -dev stdio:"$1" -rm "$2" >/dev/null 2>&1
}
```

Example:

```
> xorriso -dev trusty.iso -toc 2>/dev/null | grep -iE '^(boot|iso offers)'
Boot record  : El Torito , MBR isohybrid cyl-align-off GPT APM
Boot catalog : '/isolinux/boot.cat'
Boot image   : '/isolinux/isolinux.bin' , boot_info_table=on
Boot image   : '/boot/grub/efi.img' , platform_id=0xEF 
ISO offers   : Rock_Ridge Joliet
> xorriso -dev trusty.iso -rm autorun.inf 2>/dev/null
> xorriso -dev trusty.iso -toc 2>/dev/null | grep -iE '^(boot|iso offers)'
Boot record  : (system area only) , MBR cyl-align-off GPT APM
ISO offers   : Rock_Ridge
```

The boot stuff can be retained with `-boot_image any replay`. The joliet tree can be retained with `-joliet on` (but first one should check if it was there with `-toc`).

**Comment by slowpeek** [comment]
> @slowpeek can you provide test data for this vfs like I linked?

Right now I'm busy with other stuff. Later then

**Comment by zyv** [comment]
It's not urgent, the ticket is open since 8 years already. If you can fix other issues and provide tests, then we can finally tackle it.

**Comment by slowpeek** [comment]
> Could you please at least add tests to tests/src/vfs/extfs/helpers-list/data after such extensive changes to iso9660

Could you elaborate, what exactly do you mean? Do you want me to first modify the old code to allow testing, next modify my code for the same, next create some test input/output and ensure both old and new code pass the tests?

I dont get it how _"add tests after such extensive changes"_ is related to a piece of code with no testing at all initially.

**Comment by zyv** [comment]
> Could you elaborate, what exactly do you mean? Do you want me to first modify the old code to allow testing, next modify my code for the same, next create some test input/output and ensure both old and new code pass the tests?

This will be of course a dream course of action, but I would be absolutely happy enough to just see the tests added after the fact for the new code fixing the new behavior.
 
> I dont get it how _"add tests after such extensive changes"_ is related to a piece of code with no testing at all initially.

There are tons of untested stuff in this project (unfortunately), but as long as you don't touch it, it mostly kind of works and you never know if the "bugs" in the old code are actually bugs, or maybe workarounds for some other old bugs, which aren't even there anymore. So when extensive modifications happen, I always like to have some (new) tests to make sure that it's actually now working as desired, and hopefully will keep working as desired in the future.

P.S. I've linked an old ticket where the xorriso guy made some comments about performance improvements and his idea was to set up a service in the background to avoid repeated requests. No idea why didn't he just suggest `-exec lsdl` - maybe it didn't exist at that time, but he should have certainly known about it. Do you know when it was introduced and how good is the distro coverage at the moment?

**Comment by slowpeek** [comment]
Got it about the tests, will do.

> P.S. I've linked an old ticket where the xorriso guy made some comments about performance improvements and his idea was to set up a service in the background to avoid repeated requests. No idea why didn't he just suggest -exec lsdl - maybe it didn't exist at that time, but he should have certainly known about it. Do you know when it was introduced and how good is the distro coverage at the moment?

He was drunk mby.  lsdl is [17 years old](https://dev.lovelyhq.com/libburnia/libisoburn/commit/bc1d8d409236573e357c18fa15c1e2c2519d2b5d). Ubuntu 10.04 already has lsdl. 8.04 has no xorriso at all.

**Comment by slowpeek** [comment]
Btw it is all about `-find`, not about lsdl. `-find` does the job in a single pass, lsdl is just some print action used with find.

**Comment by slowpeek** [comment]
Added some testing, only for the xorriso part.

**Comment by zyv** [comment]
> Added some testing, only for the xorriso part.

Awesome, thank you! 👍

**Comment by zyv** [comment]
@slowpeek tests seem to be broken on Gentoo, didn't look closer into it. Might have something to do with sorting?

https://midnight-commander.org/ticket/4567

**Comment by slowpeek** [comment]
@zyv

Addressed in https://github.com/MidnightCommander/mc/pull/204

**Pull request closed without merging**
