### PR TITLE
use diff syntax highlighting for git commit messages when GIT_EDITOR=…

### PR DESCRIPTION
**Pull request by jjandresson**
…mcedit

### CODE REVIEW

**Comment by zyv** [comment]
But why?! It's just a commit message, it doesn't have diffs inside.

**Comment by jjandresson** [comment]
I use oh-my-zsh' git module which has this useful alias:

  alias gc='git commit -v'

And that in turn put the changeset you are committing into the COMMIT_MSG buffer in git diff format, and it's nice to see that syntax highlighted.

Also, if you have EDITOR=vim set, that's what vim does if you use `git commit -v`

**Comment by zyv** [comment]
@aborodin do you object? Looks nice and doesn't seem to break anything... I would merge it.

**Comment by zyv** [comment]
@aborodin also, could you please clarify before I merge what is the purpose of the two dots, like e.g.

```
file ..\*\\.(e)$ Eiffel\sSource\sFile
```

Why can't this be

```
file ^.\+\\.(e)$ Eiffel\sSource\sFile
```

if this was to mean one character or more?

It appears to me that patterns matching whole files here are all too permissive, like we recently discussed for mc.ext...

**Comment by jjandresson** [comment]
@zyv I don't understand the double period either.  I just copied the style of the other expressions in the file.  Please let me know what it is for when you find out! :)

**Comment by aborodin** [comment]
`..*` means at least one symbol in file name. Probably, the regexp engine used in mc before didn't support `+`.
As I understand, `..*` is equal to `.+`. `^` in file name isn't required, is it?

**Comment by jjandresson** [comment]
Hah!  Obvious when you say it like that, thanks :)

Most regex engines will try to match starting from the beginning of a string and only advance if they need to backtrack because the match fails before the end of the expression.   For most of the filename match expressions in `Syntax`, the `^` won't change whether or not the expression can match, but it will most likely speed things up negligibly by not backtracking and trying to match again for all subsequent character start positions in the filename.  I haven't read the code for mc's regex.c to check, but in any case I imagine that code is also an anachronism from a time before glib (and thus `GRegex`) was always linked?

**Pull request closed without merging**
