### PR TITLE
Mention hotlist navigation with 0-9 in man page

### PR DESCRIPTION
**Pull request by vfaronov**

### CODE REVIEW

**Comment by zyv** [comment]
@aborodin looks good to me, shall I simply press the merge button or what is our policy with respect to merging pull requests (as opposed to patches which have a corresponding Trac ticket)? Thanks!

**Comment by aborodin** [comment]
The 0-9 navigation works not only in hotlist but in any listbox (try that in the find file result window). So, the information in the man page should be more general.

**Comment by ghost** [comment]
Hello, I am new here. I have volunteered to help with documentation and Yury has suggested this to be my first task. I still have a lot to learn and have not yet looked at the complete sources, but I did look at the MAN source, the file associated with this bug.

I agree with @aborodin My opinion is that this type of navigation should be mentioned  and explained in the Navigation section under a new subsection called ListBox navigation - or something like that - and then that section could be referred to under the various listboxes that support it.

I could do that but have just started learning to use GitHub. If you are willing to wait for me to figure it out, I will be happy to do so. 

Thanks!

**Comment by ciampix** [comment]
Sorry I was too precipitous and I committed your patch without account for the good advice of @aborodin (damn github that provides ipnotic "commit" buttons ;-). Anyway it does not harm and add a due info. In the mean time if @davidboth is so kind he could remove this addition when the new section in the Navigation section is ready to be applied.

**Comment by ghost** [comment]
```
Certainly there is no harm done and I probably should have suggested
committing the existing patch while I learn what I need to do one of
my own. 

On 05/18/2015 11:26 AM, Marco Ciampa
  wrote:


  Sorry I was too precipitous and I committed your patch without
    account for the good advice of @aborodin
    (damn github that provides ipnotic "commit" buttons ;-). Anyway
    it does not harm and add a due info. In the mean time if @davidboth is so kind he could remove
    this addition when the new section in the Navigation section is
    ready to be applied.
  —
    Reply to this email directly or view
      it on GitHub.









-- 
```

---

David P. Both, RHCE
Millennium Technology Consulting LLC
Raleigh, NC, USA
919-389-8678

dboth@millennium-technology.com

www.millennium-technology.com 
www.databook.bz - Home of the DataBook for Linux
DataBook is a Registered Trademark of David Both

---

This communication may be unlawfully collected and stored by the National 
Security Agency (NSA) in secret. The parties to this email do not consent to the 
retrieving or storing of this communication and any related metadata, as well as 
printing, copying, re-transmitting, disseminating, or otherwise using it. If you 
believe you have received this communication in error, please delete it 
immediately.

**Comment by zyv** [comment]
@ciampix, I've had a look at the result, and ended up resetting --hard to HEAD~ and force-pushing. There haven't been any commits on top of your merge anyways, and it messed up the history in an annoying way, because apparently github's merge button doesn't rebase by default even if there is no conflict.

Anyways, no harm done. Would be nice though if we could alter the behavior of the merge button or disable it altogether.

@davidboth, please feel free to take you time to prepare a man patch on the basis of this pull request and submit it via Trac, post it to the list (or both!). I'm not monitoring the new tickets though, so if there is no reaction within a reasonable amount of time, feel free to post to the list requesting a review; I'm checking the list every once in a while, and so do the maintainers.

**Pull request merged**
