### PR TITLE
iso9660: fix truncated filenames

### PR DESCRIPTION
**Pull request by pfactum**
±1 problem results in truncating filenames in ISO file listing. This
commit fixes the issue.

### CODE REVIEW

**Comment by pfactum** [comment]
Related ticket: https://www.midnight-commander.org/ticket/3091

**Comment by aborodin** [comment]
Thanks!
Applied as 97d7bdfd77e3e7ffa4eac4307b8a47174aef7110.

**Comment by mtchuyen** [comment]
Sorry to comment this pull, I have similar issue.

I have 1 zip file, with 370 file in here, each filenames is 20char length.

I cannot use mc to see anything (enter zip file - F3, to see list child file, then F4 to show content)

- mc is newest version
- Ubuntu 22.04.2 LTS

Thanks so much

```
root@adt-be-admicro1-js-23-205:/tmp# mc --version
GNU Midnight Commander 4.8.27
Built with GLib 2.68.4
Built with S-Lang 2.3.2 with terminfo database
With builtin Editor and Aspell support
With subshell support as default
With support for background operations
With mouse support on xterm and Linux console
With support for X11 events
With internationalization support
With multiple codepages support
With ext2fs attributes support
Virtual File Systems:
 cpiofs, tarfs, sfs, extfs, ext2undelfs, ftpfs, sftpfs, fish
Data types:
 char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64;
```

**Comment by zyv** [comment]
> Sorry to comment this pull, I have similar issue.
> 
> I have 1 zip file, with 370 file in here, each filenames is 20char length.
> 
> I cannot use mc to see anything (enter zip file - F3, to see list child file, then F4 to show content)
> 
> * mc is newest version
> * Ubuntu 22.04.2 LTS
> 
> Thanks so much

Your problem description is not understandable, but it certainly has nothing to do with this issue. Maybe you mean https://bugs.launchpad.net/ubuntu/+source/mc/+bug/2062968 - if not, check latest version and report issues to our tracker and not in some random PR.

**Pull request closed without merging**
