### PR TITLE
Added yet another dark theme (yadt)

### PR DESCRIPTION
**Pull request by vorakl**
I've been using this theme for a while and consider it more convenient for me than others. It might be useful also for someone else.

### CODE REVIEW

**Comment by egmontkob** [comment]
I like it. It's very close to the modarin256-defbg theme (yes I see you mentioned it in a comment).

One issue though, not sure if it's intentional or not: You use the default background on the panels. It's great if you have a black-ish background color, that background can be seen through the panels. But it looks bad if you use a black-on-white terminal.

Maybe ship two versions just as modarin does with the normal and their -defbg counterparts??


: It looks bad if the terminal's basic colors is black text on white background. Please specify an explicit black instead of the default background for panels and such.

**Comment by egmontkob** [comment]
I like it. It's very close to the modarin256-defbg theme (yes I see you mentioned it in a comment).

One issue though, not sure if it's intentional or not: You use the default background on the panels. It's great if you have a black-ish background image, that background can be seen through the panels. But it looks bad if you use a black-on-white terminal.

Maybe ship two versions just as modarin does with the normal and their -defbg counterparts??

**Comment by vorakl** [comment]
Thanks!
Yes, makes sense! It turns to I've never seen this color theme on a white background. It's really useless ;) I've added one more skin, with a black background. More over, I added mentioning in the names that they can be used only with 256 colors support.

**Comment by timofonic** [comment]
Any news? MC has so slow commit rate these days...

**Comment by vorakl** [comment]
Nope. After the last commit to this branch 4 months ago I didn't get any news.

**Comment by zyv** [comment]
We are not looking at pull requests with any regularity and there is no way to disable this feature, unfortunately; I have now added a warning in the pull request template, hopefully, this will take care of letting people know they should use Trac instead.

Merged, thanks for the contribution.

**Pull request closed without merging**
