### PR TITLE
update PKGBUILD.syntax according to latest pacman version

### PR DESCRIPTION
**Pull request by p5n**
This commit adds msg. debug,validpgpkey,changelog,epoch and removes force keyword according to current PKGBUILD man. [\s]\* removed because of it causes a mess especially with install keyword.

### CODE REVIEW

**Comment by ossilator** [comment]
i suppose the commit is good, but what you put into the comment should be in the commit message imo.

**Comment by p5n** [comment]
I've updated commit message

**Comment by ossilator** [comment]
upon second (well, actually, third ^^) thought, you probably should split this commit - the removal of the [\s]\* doesn't seem related to the given summary at all, and could use a better description as well (without researching it myself i can't really imagine what you mean by "mess"). i'd commit that first, preserving the order of the keywords (unless you can give a good reason to change it, in particular in the same commit). then the adjustment to the new keywords.

**Comment by p5n** [comment]
I've split it

**Comment by p5n** [comment]
updated

**Comment by ossilator** [comment]
thanks, perfect.
yury, please hit the button.

**Comment by aborodin** [comment]
Please don't hit the button right now.
Commits are not on top of recent MidnightCommander:master.

**Comment by aborodin** [comment]
Thanks!
Applied as 2c37497f0e9fa1120e9d68485a70ef317bac0cd5.

**Pull request closed without merging**
